import { LocationData } from './types';

export const LOCATIONS: LocationData[] = [
  // 1. TÜRKİYE (Türkiye Turu)
  {
    id: 'tr-blue-mosque',
    name: 'Sultanahmet Camii (Sultanahmet Meydanı)',
    description: 'Osmanlı mimarisinin şaheseri, 1616 yılı yapımı ünlü 6 minareli mavi caminin meydanı.',
    country: 'Türkiye',
    lat: 41.0062,
    lng: 28.9760,
    heading: 140,
    pitch: 5,
    difficulty: 'Kolay',
    category: 'Türkiye'
  },
  {
    id: 'tr-efes',
    name: 'Efes Antik Kenti (Celsus Kütüphanesi)',
    description: 'Roma İmparatorluğu döneminin en görkemli kalıntılarından, ikonik Celsus Kütüphanesi cephesi.',
    country: 'Türkiye',
    lat: 37.9391,
    lng: 27.3414,
    heading: 90,
    pitch: 10,
    difficulty: 'Kolay',
    category: 'Türkiye'
  },
  {
    id: 'tr-cappadocia',
    name: 'Kapadokya Peri Bacaları (Göreme)',
    description: 'Doğa harikası volkanik tüf rüzgar aşınımları ve sıcak hava balonları ile meşhur vadi.',
    country: 'Türkiye',
    lat: 38.6431,
    lng: 34.8312,
    heading: 180,
    pitch: 2,
    difficulty: 'Orta',
    category: 'Türkiye'
  },
  {
    id: 'tr-pamukkale',
    name: 'Pamukkale Travertenleri',
    description: 'Kalsiyum oksit içeren termal suların oluşturduğu bembeyaz kalker traverten terasları.',
    country: 'Türkiye',
    lat: 37.9238,
    lng: 29.1187,
    heading: 320,
    pitch: -5,
    difficulty: 'Kolay',
    category: 'Türkiye'
  },
  {
    id: 'tr-anitkabir',
    name: 'Anıtkabir (Aslanlı Yol Girişi)',
    description: 'Türkiye Cumhuriyeti kurucusu Mustafa Kemal Atatürk\'ün Ankara\'daki anıt mezarı.',
    country: 'Türkiye',
    lat: 39.9250,
    lng: 32.8369,
    heading: 260,
    pitch: 3,
    difficulty: 'Kolay',
    category: 'Türkiye'
  },
  {
    id: 'tr-galata',
    name: 'Galata Kulesi',
    description: 'Cenevizliler tarafından inşa edilen, İstanbul boğazını 360 derece izleyen meşhur tarihi kule.',
    country: 'Türkiye',
    lat: 41.0256,
    lng: 28.9741,
    heading: 45,
    pitch: 15,
    difficulty: 'Kolay',
    category: 'Türkiye'
  },
  {
    id: 'tr-sumela',
    name: 'Sümela Manastırı',
    description: 'Trabzon Maçka\'da, Karadağ\'ın dik yamacına kurulmuş tarihi Rum Ortodoks manastır kompleksi.',
    country: 'Türkiye',
    lat: 40.6901,
    lng: 39.6583,
    heading: 230,
    pitch: 10,
    difficulty: 'Zor',
    category: 'Türkiye'
  },
  {
    id: 'tr-nemrut',
    name: 'Nemrut Dağı Heykelleri',
    description: 'Kommagene Kralı I. Antiochos\'un tanrılara şükran olarak yaptırdığı devasa tümülüs ve heykeller.',
    country: 'Türkiye',
    lat: 37.9801,
    lng: 38.6578,
    heading: 110,
    pitch: 5,
    difficulty: 'Zor',
    category: 'Türkiye'
  },
  {
    id: 'tr-ishakpasa',
    name: 'İshak Paşa Sarayı',
    description: 'Doğu Anadolu\'da Osmanlı, Selçuklu ve Fars mimarisinin eşsiz bir sentezini sunan tepe saray.',
    country: 'Türkiye',
    lat: 39.5203,
    lng: 44.1294,
    heading: 40,
    pitch: 8,
    difficulty: 'Orta',
    category: 'Türkiye'
  },
  {
    id: 'tr-kizkalesi',
    name: 'Mersin Kızkalesi',
    description: 'Karadan 200 metre açıkta, Akdeniz sularında yükselen efsanevi deniz kalesi.',
    country: 'Türkiye',
    lat: 36.4636,
    lng: 34.1481,
    heading: 130,
    pitch: 0,
    difficulty: 'Orta',
    category: 'Türkiye'
  },
  {
    id: 'tr-aspendos',
    name: 'Aspendos Antik Tiyatrosu',
    description: 'Antalya Serik\'te bulunan, akustik bütünlüğü günümüze kadar en iyi korunmuş Roma tiyatrosu.',
    country: 'Türkiye',
    lat: 36.9388,
    lng: 31.1720,
    heading: 350,
    pitch: 12,
    difficulty: 'Kolay',
    category: 'Türkiye'
  },
  {
    id: 'tr-uzungol',
    name: 'Uzungöl (Trabzon)',
    description: 'Yamaçlardan düşen kayaların dere ağzını kapatmasıyla oluşan meşhur Karadeniz heyelan set gölü.',
    country: 'Türkiye',
    lat: 40.6181,
    lng: 40.2917,
    heading: 15,
    pitch: 0,
    difficulty: 'Orta',
    category: 'Türkiye'
  },
  {
    id: 'tr-salda',
    name: 'Salda Gölü',
    description: 'Türkiye\'nin Maldivleri olarak anılan, turkuaz rengi suyu ve beyaz manyezit kumsallarıyla ünlü tektonik göl.',
    country: 'Türkiye',
    lat: 37.5342,
    lng: 29.6802,
    heading: 260,
    pitch: -5,
    difficulty: 'Kolay',
    category: 'Türkiye'
  },

  {
    id: 'tr-ayasofya',
    name: 'Ayasofya Camii',
    description: 'Dünya mimarlık tarihinin en görkemli ve en eski yapılarından biri.',
    country: 'Türkiye',
    lat: 41.0082,
    lng: 28.9784,
    heading: 90,
    pitch: 5,
    difficulty: 'Kolay',
    category: 'Türkiye'
  },
  {
    id: 'tr-kizkulesi',
    name: 'Kız Kulesi',
    description: 'İstanbul Boğazı\'nın tam ortasında, efsanelere konu olmuş tarihi kule.',
    country: 'Türkiye',
    lat: 41.0211,
    lng: 29.0041,
    heading: 320,
    pitch: 0,
    difficulty: 'Kolay',
    category: 'Türkiye'
  },
  {
    id: 'tr-gobeklitepe',
    name: 'Göbeklitepe',
    description: 'Tarihin sıfır noktası kabul edilen, dünyanın bilinen en eski tapınak merkezi.',
    country: 'Türkiye',
    lat: 37.2231,
    lng: 38.9225,
    heading: 0,
    pitch: 0,
    difficulty: 'Orta',
    category: 'Türkiye'
  },
  {
    id: 'tr-mevlana',
    name: 'Mevlana Müzesi',
    description: 'Mevlana Celaleddin Rumi\'nin türbesinin yer aldığı, yeşil kubbesiyle ünlü külliye.',
    country: 'Türkiye',
    lat: 37.8707,
    lng: 32.5050,
    heading: 45,
    pitch: 5,
    difficulty: 'Kolay',
    category: 'Türkiye'
  },
  {
    id: 'tr-bodrum-kale',
    name: 'Bodrum Kalesi',
    description: 'Saint Jean Şövalyeleri tarafından inşa edilmiş, günümüzde Sualtı Arkeoloji Müzesi olan kale.',
    country: 'Türkiye',
    lat: 37.0316,
    lng: 27.4294,
    heading: 150,
    pitch: 0,
    difficulty: 'Orta',
    category: 'Türkiye'
  },
  {
    id: 'tr-safranbolu',
    name: 'Safranbolu Evleri',
    description: 'Geleneksel Osmanlı sivil mimarisinin en güzel örneklerini sunan tarihi konaklar.',
    country: 'Türkiye',
    lat: 41.2464,
    lng: 32.6934,
    heading: 260,
    pitch: -5,
    difficulty: 'Orta',
    category: 'Türkiye'
  },
  {
    id: 'tr-truva',
    name: 'Truva Antik Kenti (Truva Atı)',
    description: 'Homeros\'un İlyada destanına konu olan ve efsanevi Truva Atı\'nın bulunduğu tarihi şehir.',
    country: 'Türkiye',
    lat: 39.9575,
    lng: 26.2389,
    heading: 120,
    pitch: 0,
    difficulty: 'Orta',
    category: 'Türkiye'
  },
  {
    id: 'tr-sirince',
    name: 'Şirince Köyü',
    description: 'Tarihi Rum evleri, taş sokakları ve bağlarıyla ünlü turistik Ege köyü.',
    country: 'Türkiye',
    lat: 37.9427,
    lng: 27.3976,
    heading: 180,
    pitch: 0,
    difficulty: 'Zor',
    category: 'Türkiye'
  },
  {
    id: 'tr-balikligol',
    name: 'Balıklıgöl (Halil-ür Rahman)',
    description: 'Şanlıurfa\'da bulunan, Hz. İbrahim efsanesiyle bilinen ve kutsal sayılan balıkların bulunduğu havuz.',
    country: 'Türkiye',
    lat: 37.1481,
    lng: 38.7846,
    heading: 90,
    pitch: 5,
    difficulty: 'Kolay',
    category: 'Türkiye'
  },
  {
    id: 'tr-mardin-eski',
    name: 'Eski Mardin Evleri',
    description: 'Mezopotamya ovasına bakan dağ yamacında teraslar halinde sıralanmış taş işçiliğinin zirvesi konaklar.',
    country: 'Türkiye',
    lat: 37.3129,
    lng: 40.7339,
    heading: 230,
    pitch: -5,
    difficulty: 'Orta',
    category: 'Türkiye'
  },
  {
    id: 'tr-ani',
    name: 'Ani Harabeleri',
    description: 'Kars sınırında, Arpaçay kenarında bulunan, tarihi İpek Yolu üzerindeki görkemli hayalet şehir.',
    country: 'Türkiye',
    lat: 40.5074,
    lng: 43.5724,
    heading: 310,
    pitch: 0,
    difficulty: 'Zor',
    category: 'Türkiye'
  },
  {
    id: 'tr-ortakoy',
    name: 'Ortaköy Camii ve Boğaziçi Köprüsü',
    description: 'Neo-Barok mimarisi ve arkasındaki devasa Boğaziçi Köprüsü siluetiyle İstanbul\'un klasik manzarası.',
    country: 'Türkiye',
    lat: 41.0474,
    lng: 29.0272,
    heading: 45,
    pitch: 10,
    difficulty: 'Kolay',
    category: 'Türkiye'
  },
  {
    id: 'tr-zeuma',
    name: 'Zeugma Mozaik Müzesi',
    description: 'Gaziantep\'te yer alan, ünlü Çingene Kızı mozaiğine ev sahipliği yapan devasa müze alanı.',
    country: 'Türkiye',
    lat: 37.0754,
    lng: 37.3853,
    heading: 0,
    pitch: 0,
    difficulty: 'Zor',
    category: 'Türkiye'
  },
  {
    id: 'tr-mount-ararat',
    name: 'Ağrı Dağı (İshakpaşa Yolu)',
    description: 'Efsanevi Nuh\'un Gemisi\'nin oturduğuna inanılan, 5137 metre yüksekliğiyle Türkiye\'nin çatısı.',
    country: 'Türkiye',
    lat: 39.5599,
    lng: 44.0204,
    heading: 80,
    pitch: 5,
    difficulty: 'Zor',
    category: 'Türkiye'
  },

  // 2. FAMOUS PLACES (Dünya Turu / Meşhur Yerler)
  {
    id: 'world-eiffel',
    name: 'Eiffel Kulesi, Paris',
    description: 'Fransa\'nın sembolü olan, 1889 yılında açılmış demir örgü anıtsal kule kafesi.',
    country: 'Fransa',
    lat: 48.8582,
    lng: 2.2944,
    heading: 320,
    pitch: 35,
    difficulty: 'Kolay',
    category: 'Dünya'
  },
  {
    id: 'world-colosseum',
    name: 'Kolezyum, Roma',
    description: 'İtalya\'da bulunan, Roma İmparatorluğu\'nun amfitiyatro ve gladyatör dövüş arenası.',
    country: 'İtalya',
    lat: 41.8902,
    lng: 12.4922,
    heading: 140,
    pitch: 8,
    difficulty: 'Kolay',
    category: 'Dünya'
  },
  {
    id: 'world-taj-mahal',
    name: 'Tac Mahal, Agra',
    description: 'Babür İmparatoru Şah Cihan\'ın eşi Mümtaz Mahal anısına beyaz mermerden yaptırdığı görkemli anıt mezar.',
    country: 'Hindistan',
    lat: 27.1751,
    lng: 78.0421,
    heading: 0,
    pitch: 10,
    difficulty: 'Kolay',
    category: 'Dünya'
  },
  {
    id: 'world-opera-house',
    name: 'Sidney Opera Evi',
    description: 'Yelken şeklindeki çatı tasarımıyla modern mimarinin ve Avustralya kıtasının en ünlü yapıtı.',
    country: 'Avustralya',
    lat: -33.8568,
    lng: 151.2153,
    heading: 240,
    pitch: 2,
    difficulty: 'Kolay',
    category: 'Dünya'
  },
  {
    id: 'world-liberty',
    name: 'Özgürlük Heykeli, New York',
    description: 'Fransa\'nın ABD\'ye hediye ettiği, göçmenleri ve özgürlüğü temsil eden ikonik anıt heykel.',
    country: 'ABD',
    lat: 40.6892,
    lng: -74.0445,
    heading: 10,
    pitch: 12,
    difficulty: 'Kolay',
    category: 'Dünya'
  },
  {
    id: 'world-pyramids',
    name: 'Gize Piramitleri (Büyük Keops)',
    description: 'Dünyanın yedi harikasından ayakta kalan tek yapı olan devasa antik Mısır firavun piramitleri.',
    country: 'Mısır',
    lat: 29.9792,
    lng: 31.1342,
    heading: 240,
    pitch: 15,
    difficulty: 'Orta',
    category: 'Dünya'
  },
  {
    id: 'world-christ-redeemer',
    name: 'Kurtarıcı İsa Heykeli (Rio de Janeiro)',
    description: 'Corcovado Dağı\'nın tepesinde, kollarını şehre açan devasa betonarme İsa heykeli.',
    country: 'Brezilya',
    lat: -22.9519,
    lng: -43.2105,
    heading: 220,
    pitch: 20,
    difficulty: 'Orta',
    category: 'Dünya'
  },
  {
    id: 'world-leaning-pisa',
    name: 'Pisa Kulesi',
    description: 'İnşa edildiği toprak yapısındaki çöküş sebebiyle eğik durmasıyla ünlenen İtalyan çan kulesi.',
    country: 'İtalya',
    lat: 43.7230,
    lng: 10.3966,
    heading: 10,
    pitch: 18,
    difficulty: 'Kolay',
    category: 'Dünya'
  },
  {
    id: 'world-sagrada-familia',
    name: 'Sagrada Familia Bazilikası',
    description: 'Mimar Antoni Gaudí\'nin ömrünü adadığı, Barselona\'daki tamamlanamayan sıra dışı katedral.',
    country: 'İspanya',
    lat: 41.4036,
    lng: 2.1744,
    heading: 15,
    pitch: 25,
    difficulty: 'Kolay',
    category: 'Dünya'
  },
  {
    id: 'world-machu-picchu',
    name: 'Machu Picchu Antik Kenti',
    description: 'And Dağları\'nın zirvesinde, 15. yüzyılda İnka medeniyeti tarafından korunma amaçlı kurulan kayıp şehir.',
    country: 'Peru',
    lat: -13.1631,
    lng: -72.5450,
    heading: 45,
    pitch: 5,
    difficulty: 'Zor',
    category: 'Dünya'
  },
  {
    id: 'world-petra',
    name: 'Petra Antik Kenti',
    description: 'Ürdün kanyon yarıkları içine doğrudan gül pembesi kaya blokları oyularak kurulan Nebati şehri.',
    country: 'Ürdün',
    lat: 30.3285,
    lng: 35.4415,
    heading: 80,
    pitch: 5,
    difficulty: 'Zor',
    category: 'Dünya'
  },

  // 3. UNITED STATES (ABD)
  {
    id: 'us-times-square',
    name: 'Times Square, New York',
    description: 'Dünyanın en yoğun yaya trafiğine, devasa dijital panolara ve tiyatrolara ev sahipliği yapan kavşak.',
    country: 'ABD',
    lat: 40.7580,
    lng: -73.9855,
    heading: 180,
    pitch: 10,
    difficulty: 'Kolay',
    category: 'ABD'
  },
  {
    id: 'us-golden-gate',
    name: 'Golden Gate Köprüsü, San Francisco',
    description: 'San Francisco körfezi girişinde bulunan kızıl renkli dünyaca ünlü asma köprü.',
    country: 'ABD',
    lat: 37.8199,
    lng: -122.4783,
    heading: 355,
    pitch: 0,
    difficulty: 'Kolay',
    category: 'ABD'
  },
  {
    id: 'us-grand-canyon',
    name: 'Grand Canyon (Mather Point)',
    description: 'Colorado Nehri\'nin milyonlarca yılda yardığı Arizona eyaletindeki devasa tabiat harikası kanyon.',
    country: 'ABD',
    lat: 36.0617,
    lng: -112.1077,
    heading: 30,
    pitch: -5,
    difficulty: 'Orta',
    category: 'ABD'
  },
  {
    id: 'us-las-vegas',
    name: 'Las Vegas Strip (Bellagio önü)',
    description: 'Casinoları, dev otelleri ve Bellagio çeşmeleri ile meşhur gecesi gündüzü ışıltılı büyük Strip bulvarı.',
    country: 'ABD',
    lat: 36.1126,
    lng: -115.1725,
    heading: 190,
    pitch: 2,
    difficulty: 'Orta',
    category: 'ABD'
  },
  {
    id: 'us-hollywood',
    name: 'Hollywood Walk of Fame',
    description: 'Los Angeles\'ta kaldırım üzerinde ünlü sanatçıların isimlerinin yazılı olduğu yıldızların bulunduğu cadde.',
    country: 'ABD',
    lat: 34.1016,
    lng: -118.3268,
    heading: 90,
    pitch: -15,
    difficulty: 'Orta',
    category: 'ABD'
  },

  // 4. JAPAN (Japonya)
  {
    id: 'jp-shibuya',
    name: 'Shibuya Crossing, Tokyo',
    description: 'Aynı anda binlerce yayanın karşıdan karşıya geçtiği dünyanın en meşhur yaya geçidi.',
    country: 'Japonya',
    lat: 35.6595,
    lng: 139.7005,
    heading: 110,
    pitch: 5,
    difficulty: 'Kolay',
    category: 'Japonya'
  },
  {
    id: 'jp-fuji',
    name: 'Fuji Dağı (Yamacından Manzara)',
    description: 'Japonya\'nın en kutsal simgesi olan simetrik, kar kaplı görkemli volkanik dağ.',
    country: 'Japonya',
    lat: 35.3606,
    lng: 138.7274,
    heading: 160,
    pitch: 5,
    difficulty: 'Orta',
    category: 'Japonya'
  },
  {
    id: 'jp-kinkakuji',
    name: 'Altın Köşk Tapınağı (Kinkaku-ji), Kyoto',
    description: 'Üst iki katı tamamen altın varaklarla kaplanmış, gölet ortasında yer alan nefes kesici Zen tapınağı.',
    country: 'Japonya',
    lat: 35.0394,
    lng: 135.7292,
    heading: 220,
    pitch: 2,
    difficulty: 'Orta',
    category: 'Japonya'
  },
  {
    id: 'jp-dotonbori',
    name: 'Dotonbori Kanalı, Osaka',
    description: 'Gashaponlar, kocaman neon tabelalar ve ünlü koşan sporcu (Glico Man) reklamı ile ünlü eğlence caddesi.',
    country: 'Japonya',
    lat: 34.6687,
    lng: 135.5013,
    heading: 270,
    pitch: 3,
    difficulty: 'Kolay',
    category: 'Japonya'
  },
  {
    id: 'jp-itsukushima',
    name: 'Itsukushima Şinto Tapınağı (Yüzen Tori)',
    description: 'Suların yükselmesiyle denizde yüzüyormuş gibi görünen devasa kırmızı ahşap Şinto kapısı.',
    country: 'Japonya',
    lat: 34.2960,
    lng: 132.3199,
    heading: 140,
    pitch: 0,
    difficulty: 'Zor',
    category: 'Japonya'
  },

  // 5. UNITED KINGDOM (Birleşik Krallık)
  {
    id: 'uk-big-ben',
    name: 'Big Ben & Westminster Sarayı, Londra',
    description: 'Elizabeth Kulesi olarak da bilinen ikonik saat kulesi ve parlamento binası önü.',
    country: 'Birleşik Krallık',
    lat: 51.5007,
    lng: -0.1246,
    heading: 70,
    pitch: 10,
    difficulty: 'Kolay',
    category: 'Birleşik Krallık'
  },
  {
    id: 'uk-tower-bridge',
    name: 'Tower Bridge, Londra',
    description: 'Thames Nehri üzerinde yükselen, Gotik tarzda kuleleri olan Viktorya dönemi açılır-kapanır asma köprüsü.',
    country: 'Birleşik Krallık',
    lat: 51.5055,
    lng: -0.0754,
    heading: 190,
    pitch: 8,
    difficulty: 'Kolay',
    category: 'Birleşik Krallık'
  },
  {
    id: 'uk-stonehenge',
    name: 'Stonehenge Tarihi Alanı',
    description: 'Milattan önce inşa edilmiş esrarengiz neolitik anıtsal dikilitaş dairesi.',
    country: 'Birleşik Krallık',
    lat: 51.1789,
    lng: -1.8262,
    heading: 120,
    pitch: 2,
    difficulty: 'Orta',
    category: 'Birleşik Krallık'
  },
  {
    id: 'uk-edinburgh-castle',
    name: 'Edinburgh Kalesi, İskoçya',
    description: 'Volkanik bir kaya tepesinin üstünde yer alan, İskoçya başkentinin tarihi sembol kalesi.',
    country: 'Birleşik Krallık',
    lat: 55.9486,
    lng: -3.1999,
    heading: 80,
    pitch: 5,
    difficulty: 'Orta',
    category: 'Birleşik Krallık'
  },
  {
    id: 'uk-giant-causeway',
    name: 'Devler Kaldırımı, Kuzey İrlanda',
    description: 'Eski volkanik patlamalar sonucu oluşmuş binlerce simetrik altıgen bazalt sütundan oluşan sahil şeridi.',
    country: 'Birleşik Krallık',
    lat: 55.2408,
    lng: -6.5116,
    heading: 320,
    pitch: -5,
    difficulty: 'Zor',
    category: 'Birleşik Krallık'
  },

  // 6. FRANCE (Fransa)
  {
    id: 'fr-eiffel-champ',
    name: 'Champ de Mars (Eiffel Manzarası), Paris',
    description: 'Eyfel Kulesi\'nin hemen önündeki geniş yeşil park alanı ve meydan.',
    country: 'Fransa',
    lat: 48.8556,
    lng: 2.2986,
    heading: 310,
    pitch: 25,
    difficulty: 'Kolay',
    category: 'Fransa'
  },
  {
    id: 'fr-louvre',
    name: 'Louvre Müzesi Avlusu (Cam Piramit)',
    description: 'Dünyanın en büyük sanat müzesinin bahçesinde yer alan meşhur cam ve metal piramit tasarımı.',
    country: 'Fransa',
    lat: 48.8606,
    lng: 2.3376,
    heading: 260,
    pitch: 6,
    difficulty: 'Kolay',
    category: 'Fransa'
  },
  {
    id: 'fr-versailles',
    name: 'Versay Sarayı Bahçeleri',
    description: 'Güneş Kral XIV. Louis tarafından yaptırılan, barok mimarinin ve simetrik peyzajın zirvesi olan saray havuzları.',
    country: 'Fransa',
    lat: 48.8048,
    lng: 2.1120,
    heading: 270,
    pitch: 2,
    difficulty: 'Orta',
    category: 'Fransa'
  },
  {
    id: 'fr-nice-promenade',
    name: 'Promenade des Anglais, Nice',
    description: 'Nice şehrinde Akdeniz turkuaz suları boyunca uzanan palmiyeli ünlü sahil yürüyüş kordonu.',
    country: 'Fransa',
    lat: 43.6942,
    lng: 7.2568,
    heading: 90,
    pitch: 0,
    difficulty: 'Orta',
    category: 'Fransa'
  },
  {
    id: 'fr-mont-saint-michel',
    name: 'Mont Saint-Michel Adası',
    description: 'Normandiya kıyısında suların yükselmesiyle ada, alçalmasıyla tepe olan rüya gibi Gotik kale-manastır.',
    country: 'Fransa',
    lat: 48.6360,
    lng: -1.5114,
    heading: 350,
    pitch: 5,
    difficulty: 'Zor',
    category: 'Fransa'
  },

  // 7. SPAIN (İspanya)
  {
    id: 'es-sagrada',
    name: 'La Sagrada Familia Katedrali, Barselona',
    description: 'Antoni Gaudi\'nin doğadan esinlenerek tasarladığı ve yapımı hala süren görkemli bazilika cephesi.',
    country: 'İspanya',
    lat: 41.4036,
    lng: 2.1744,
    heading: 10,
    pitch: 30,
    difficulty: 'Kolay',
    category: 'İspanya'
  },
  {
    id: 'es-park-guell',
    name: 'Park Güell Terası, Barselona',
    description: 'Gaudi\'nin renkli seramik mozaik bankları ve Barselona manzarasını sunan ünlü teras bahçesi.',
    country: 'İspanya',
    lat: 41.4144,
    lng: 2.1527,
    heading: 150,
    pitch: -2,
    difficulty: 'Kolay',
    category: 'İspanya'
  },
  {
    id: 'es-plaza-mayor',
    name: 'Plaza Mayor, Madrid',
    description: 'Madrid\'in merkezinde çevresi simetrik 3 katlı tarihi konak binalarla çevrili meşhur revaklı meydan.',
    country: 'İspanya',
    lat: 40.4154,
    lng: -3.7074,
    heading: 45,
    pitch: 3,
    difficulty: 'Orta',
    category: 'İspanya'
  },
  {
    id: 'es-alhambra',
    name: 'El Hamra Sarayı (Alhambra), Granada',
    description: 'Endülüs Emevileri dönemine ait İslam sanatının dünyadaki en nadide ve detaylı kale-saray eseri.',
    country: 'İspanya',
    lat: 37.1760,
    lng: -3.5855,
    heading: 260,
    pitch: 2,
    difficulty: 'Zor',
    category: 'İspanya'
  },
  {
    id: 'es-seville-plaza',
    name: 'Plaza de España, Sevilla',
    description: 'Yarım daire şeklinde tasarlanmış, her İspanyol eyaleti için özel yapılmış çinili nişleri olan muhteşef meydan.',
    country: 'İspanya',
    lat: 37.3772,
    lng: -5.9869,
    heading: 320,
    pitch: 5,
    difficulty: 'Orta',
    category: 'İspanya'
  },

  // 8. GERMANY (Almanya)
  {
    id: 'de-brandenburg',
    name: 'Brandenburg Kapısı, Berlin',
    description: 'Berlin\'in tarihi zafer takı ve doğu-batı birleşmesinin evrensel barış sembolü.',
    country: 'Almanya',
    lat: 52.5163,
    lng: 13.3777,
    heading: 270,
    pitch: 2,
    difficulty: 'Kolay',
    category: 'Almanya'
  },
  {
    id: 'de-neuschwanstein',
    name: 'Neuschwanstein Şatosu, Bavyera',
    description: 'Disneyland logosuna ilham veren, Bavyera Alplerinin dik yamacındaki masalsı neo-romantik şato.',
    country: 'Almanya',
    lat: 47.5576,
    lng: 10.7498,
    heading: 100,
    pitch: 10,
    difficulty: 'Orta',
    category: 'Almanya'
  },
  {
    id: 'de-cologne-cathedral',
    name: 'Köln Katedrali (Kölner Dom)',
    description: 'Gotik mimarinin devasa çift kuleli şaheseri olan, Ren Nehri kenarındaki muhteşem katedral meydanı.',
    country: 'Almanya',
    lat: 50.9413,
    lng: 6.9583,
    heading: 120,
    pitch: 25,
    difficulty: 'Kolay',
    category: 'Almanya'
  },
  {
    id: 'de-marienplatz',
    name: 'Marienplatz, Münih',
    description: 'Münih merkezinde yer alan, devasa Yeni Belediye Binası (Neues Rathaus) ve Glockenspiel saat kulesi önü.',
    country: 'Almanya',
    lat: 48.1374,
    lng: 11.5755,
    heading: 340,
    pitch: 12,
    difficulty: 'Kolay',
    category: 'Almanya'
  },
  {
    id: 'de-reichstag',
    name: 'Reichstag Parlamento Binası, Berlin',
    description: 'Savaş sonrası restore edilmiş cam kubbesiyle ünlü, Federal Alman Meclisi binası ve yeşil ön bahçesi.',
    country: 'Almanya',
    lat: 52.5186,
    lng: 13.3762,
    heading: 100,
    pitch: 10,
    difficulty: 'Orta',
    category: 'Almanya'
  },

  // 9. CANADA (Kanada)
  {
    id: 'ca-niagara',
    name: 'Niagara Şelaleleri (Kanada Tarafı)',
    description: 'Erie ve Ontario göllerini bağlayan, Horseshoe olarak adlandırılan nallar şeklindeki görkemli şelale.',
    country: 'Kanada',
    lat: 43.0799,
    lng: -79.0747,
    heading: 140,
    pitch: -5,
    difficulty: 'Kolay',
    category: 'Kanada'
  },
  {
    id: 'ca-cn-tower',
    name: 'CN Kulesi Tabanı, Toronto',
    description: 'Bir dönem dünyanın en yüksek bağımsız yapısı unvanına sahip olan 553 metrelik telekomünikasyon kulesi.',
    country: 'Kanada',
    lat: 43.6426,
    lng: -79.3871,
    heading: 320,
    pitch: 35,
    difficulty: 'Kolay',
    category: 'Kanada'
  },
  {
    id: 'ca-banff',
    name: 'Banff Ulusal Parkı (Moraine Gölü)',
    description: 'Kayalık dağlar (Rocky Mountains) arasında yer alan, buzul unundan ötürü turkuaz renkli eşsiz göl vadisi.',
    country: 'Kanada',
    lat: 51.3217,
    lng: -116.1860,
    heading: 190,
    pitch: 5,
    difficulty: 'Zor',
    category: 'Kanada'
  },
  {
    id: 'ca-parliament',
    name: 'Parlamento Tepesi, Ottawa',
    description: 'Gothic-revival tarzında neo-gotik tarzdaki kuleleriyle Kanada federal hükümet binaları meydanı.',
    country: 'Kanada',
    lat: 45.4248,
    lng: -75.7001,
    heading: 160,
    pitch: 5,
    difficulty: 'Orta',
    category: 'Kanada'
  },
  {
    id: 'ca-vancouver',
    name: 'Stanley Park Seawall, Vancouver',
    description: 'Vancouver şehir silueti, okyanus suyu ve asma köprü manzarasını birleştiren tarihi sahil bisiklet yolu.',
    country: 'Kanada',
    lat: 49.3001,
    lng: -123.1311,
    heading: 130,
    pitch: 1,
    difficulty: 'Orta',
    category: 'Kanada'
  },

  // 10. POLAND (Polonya)
  {
    id: 'pl-rynek-krakow',
    name: 'Rynek Glowny Meydanı, Krakow',
    description: 'Avrupa\'nın en büyük orta çağ pazar meydanlarından, ortasındaki Kumaş Pazarı (Sukiennice) binası.',
    country: 'Polonya',
    lat: 50.0614,
    lng: 19.9380,
    heading: 45,
    pitch: 3,
    difficulty: 'Kolay',
    category: 'Polonya'
  },
  {
    id: 'pl-warsaw-old',
    name: 'Eski Şehir (Stare Miasto) Meydanı, Varşova',
    description: 'İkinci dünya savaşında tamamen yıkıldıktan sonra aslına uygun restore edilen renkli tarihi Varşova evleri.',
    country: 'Polonya',
    lat: 52.2497,
    lng: 21.0122,
    heading: 120,
    pitch: 2,
    difficulty: 'Orta',
    category: 'Polonya'
  },
  {
    id: 'pl-gdansk-crane',
    name: 'Gdansk Tarihi Vinç (Zuraw)',
    description: 'Motlawa Nehri kenarında yer alan, orta çağ Avrupa\'sının en büyük ahşap liman vinci ve sokakları.',
    country: 'Polonya',
    lat: 54.3508,
    lng: 18.6578,
    heading: 330,
    pitch: 5,
    difficulty: 'Orta',
    category: 'Polonya'
  },
  {
    id: 'pl-culture-palace',
    name: 'Kültür ve Bilim Sarayı, Varşova',
    description: 'Sovyet mimarı tarzında inşa edilen Polonya\'nın en yüksek ve tartışmalı anıtsal gökdeleni.',
    country: 'Polonya',
    lat: 52.2318,
    lng: 21.0060,
    heading: 210,
    pitch: 15,
    difficulty: 'Kolay',
    category: 'Polonya'
  },
  {
    id: 'pl-wroclaw-dwarfs',
    name: 'Wroclaw Pazar Meydanı',
    description: 'Nefis Gotik Belediye binaları ve şehrin her yanına yayılmış minik bronz cüce heykelleriyle ünlü meydan.',
    country: 'Polonya',
    lat: 51.1095,
    lng: 17.0318,
    heading: 180,
    pitch: 4,
    difficulty: 'Zor',
    category: 'Polonya'
  },

  // 11. ITALY (İtalya)
  {
    id: 'it-colosseum',
    name: 'Kolezyum Dış Çevresi, Roma',
    description: 'Flavianus amfitiyatrosu olarak bilinen, Roma İmparatorluğu\'nun taş ve beton gladyatör arenası dışı.',
    country: 'İtalya',
    lat: 41.8902,
    lng: 12.4922,
    heading: 130,
    pitch: 10,
    difficulty: 'Kolay',
    category: 'İtalya'
  },
  {
    id: 'it-venice-canal',
    name: 'Büyük Kanal (Canal Grande), Venedik',
    description: 'Gondollar, tarihi Venedik saray cepheleri ve suyun üzerinde süzülen teknelerin göründüğü su yolu.',
    country: 'İtalya',
    lat: 45.4371,
    lng: 12.3326,
    heading: 260,
    pitch: 0,
    difficulty: 'Kolay',
    category: 'İtalya'
  },
  {
    id: 'it-florence-duomo',
    name: 'Floransa Duomo Katedrali',
    description: 'Brunelleschi tarafından yapılan devasa tuğla renkli kubbesi ve beyaz-yeşil mermer işlemeli ön cephesi.',
    country: 'İtalya',
    lat: 43.7731,
    lng: 11.2560,
    heading: 110,
    pitch: 20,
    difficulty: 'Kolay',
    category: 'İtalya'
  },
  {
    id: 'it-amalfi',
    name: 'Positano (Amalfi Kıyıları)',
    description: 'Dik kayalar üzerine pastel renklerle üst üste inşa edilmiş dik binalar ve Akdeniz kıyı virajları.',
    country: 'İtalya',
    lat: 40.6281,
    lng: 14.4850,
    heading: 340,
    pitch: 8,
    difficulty: 'Zor',
    category: 'İtalya'
  },
  {
    id: 'it-trevi',
    name: 'Trevi Aşk Çeşmesi, Roma',
    description: 'Arka plandaki Poli Sarayı cephesini kaplayan, heykellerle süslü ünlü barok çeşme havuzu.',
    country: 'İtalya',
    lat: 41.9009,
    lng: 12.4833,
    heading: 170,
    pitch: 8,
    difficulty: 'Kolay',
    category: 'İtalya'
  },

  // 12. RUSSIA (Rusya)
  {
    id: 'ru-red-square',
    name: 'Kızıl Meydan & Aziz Vasil Katedrali, Moskova',
    description: 'Moskova\'nın simgesi olan, rengarenk soğan tipi benekli kubbeleriyle meşhur masalsı katedral.',
    country: 'Rusya',
    lat: 55.7525,
    lng: 37.6231,
    heading: 140,
    pitch: 5,
    difficulty: 'Kolay',
    category: 'Rusya'
  },
  {
    id: 'ru-kremlin',
    name: 'Kremlin Sarayı Surları',
    description: 'Kızıl Meydan\'da Moskova nehri kıyısında yükselen kızıl tuğla duvarlı devasa Rus yönetim kompleksi.',
    country: 'Rusya',
    lat: 55.7517,
    lng: 37.6178,
    heading: 210,
    pitch: 3,
    difficulty: 'Orta',
    category: 'Rusya'
  },
  {
    id: 'ru-hermitage',
    name: 'Ermitaj (Kışlık Saray) Meydanı, St. Petersburg',
    description: 'Çarlık Rusyası\'nın simgesi barok yeşil-beyaz Kışlık Saray cephesi ve meydandaki devasa sütun.',
    country: 'Rusya',
    lat: 59.9390,
    lng: 30.3158,
    heading: 345,
    pitch: 5,
    difficulty: 'Orta',
    category: 'Rusya'
  },
  {
    id: 'ru-peterhof',
    name: 'Peterhof Sarayı Altın Çeşmeleri',
    description: 'St. Petersburg dışında, okyanusa paralel uzanan muazzam altın heykelli fıskiyeler silsilesi saray bahçesi.',
    country: 'Rusya',
    lat: 59.8845,
    lng: 29.9086,
    heading: 180,
    pitch: 3,
    difficulty: 'Zor',
    category: 'Rusya'
  },

  // 13. BRAZIL (Brezilya)
  {
    id: 'br-christ',
    name: 'Kurtarıcı İsa Heykeli (Corcovado), Rio',
    description: 'Rio de Janeiro şehrini tepeden izleyen, okyanusa karşı kollarını açmış devasa İsa anıtı dibi.',
    country: 'Brezilya',
    lat: -22.9519,
    lng: -43.2105,
    heading: 180,
    pitch: 30,
    difficulty: 'Kolay',
    category: 'Brezilya'
  },
  {
    id: 'br-copacabana',
    name: 'Copacabana Plajı Kordonu',
    description: 'Rio\'da dalgalı siyah beyaz mozaik kaldırım deseniyle ünlü okyanus plaj kordonu geniş caddesi.',
    country: 'Brezilya',
    lat: -22.9714,
    lng: -43.1852,
    heading: 30,
    pitch: 0,
    difficulty: 'Orta',
    category: 'Brezilya'
  },
  {
    id: 'br-iguazu',
    name: 'Iguazu Şelaleleri (Brezilya Tarafı)',
    description: 'Arjantin ve Brezilya sınırındaki, yüzlerce kollu debisi yüksek devasa şelale kanyon kordonu.',
    country: 'Brezilya',
    lat: -25.6903,
    lng: -54.4367,
    heading: 260,
    pitch: -3,
    difficulty: 'Zor',
    category: 'Brezilya'
  },
  {
    id: 'br-salvador',
    name: 'Pelourinho Tarihi Mahallesi, Salvador',
    description: 'Portekiz sömürge dönemi esintili rengarenk Arnavut kaldırımlı yokuşları ve kiliseleri.',
    country: 'Brezilya',
    lat: -12.9714,
    lng: -38.5081,
    heading: 130,
    pitch: 5,
    difficulty: 'Zor',
    category: 'Brezilya'
  },

  // 14. AUSTRALIA (Avustralya)
  {
    id: 'au-opera-house',
    name: 'Sidney Opera Evi (Liman Manzarası)',
    description: 'Sidney liman köprüsünün ve beyaz fütüristik kıvrımlı opera kabuklarının görülebildiği rıhtım.',
    country: 'Avustralya',
    lat: -33.8568,
    lng: 151.2153,
    heading: 210,
    pitch: 10,
    difficulty: 'Kolay',
    category: 'Avustralya'
  },
  {
    id: 'au-sydney-bridge',
    name: 'Sydney Harbour Bridge',
    description: 'Limanın iki yakasını birleştiren "Coathanger" (Elbise Askısı) lakaplı dev çelik kemerli köprü.',
    country: 'Avustralya',
    lat: -33.8523,
    lng: 151.2108,
    heading: 320,
    pitch: 8,
    difficulty: 'Kolay',
    category: 'Avustralya'
  },
  {
    id: 'au-melbourne-street',
    name: 'Fitzroy Graffiti Sokakları, Melbourne',
    description: 'Graffitilerle bezenmiş dar arnavut kaldırımları ve Avustralya sokak tabelası.',
    country: 'Avustralya',
    lat: -37.8015,
    lng: 144.9788,
    heading: 30,
    pitch: 0,
    difficulty: 'Orta',
    category: 'Avustralya'
  },
  {
    id: 'au-twelve-apostles',
    name: 'Twelve Apostles, Great Ocean Road',
    description: 'Okyanustan dimdik fışkıran devasa kireçtaşı sütunları ve muazzam falez kıyı yolu.',
    country: 'Avustralya',
    lat: -38.6655,
    lng: 143.1044,
    heading: 230,
    pitch: -2,
    difficulty: 'Zor',
    category: 'Avustralya'
  },
  {
    id: 'au-royal-botanic',
    name: 'Kraliyet Botanik Bahçeleri, Sidney',
    description: 'Sidney limanı kıyısında, tropikal palmiyeler ile sarmalanmış ve arka planda modern gökdelenlerin yükseldiği prestijli bahçe yolu.',
    country: 'Avustralya',
    lat: -33.8642,
    lng: 151.2166,
    heading: 340,
    pitch: 5,
    difficulty: 'Kolay',
    category: 'Avustralya'
  },
  {
    id: 'au-uluru-base',
    name: 'Uluru Kutsal Taş Alanı (Ayers Rock)',
    description: 'Avustralya iç çöllerinde (Outback) yükselen dev kırmızı kumtaşı kayası ve etrafındaki kuru çalılıklar.',
    country: 'Avustralya',
    lat: -25.3444,
    lng: 131.0369,
    heading: 120,
    pitch: 2,
    difficulty: 'Zor',
    category: 'Avustralya'
  },
  {
    id: 'au-bondi-beach',
    name: 'Bondi Plajı Sörf Sahili',
    description: 'Sörfçülerin ve güneşlenenlerin doldurduğu, ünlü altın kumlu Bondi sahili ve dalgalı turkuaz Tasman denizi.',
    country: 'Avustralya',
    lat: -33.8915,
    lng: 151.2767,
    heading: 90,
    pitch: -3,
    difficulty: 'Kolay',
    category: 'Avustralya'
  },
  {
    id: 'au-surfers-paradise',
    name: 'Surfers Paradise Sahil Kordonu, Gold Coast',
    description: 'Doğrudan kumsal kıyısından göğe yükselen dev cam gökdelenler ile çevrili ünlü sörf metropolü sahil yolu.',
    country: 'Avustralya',
    lat: -28.0016,
    lng: 153.4300,
    heading: 10,
    pitch: 5,
    difficulty: 'Orta',
    category: 'Avustralya'
  },

  // 15. INDONESIA (Endonezya)
  {
    id: 'id-borobudur',
    name: 'Borobudur Budist Tapınağı, Java',
    description: 'Çan şeklindeki stupaları içinde Buda heykellerini barındıran dünyanın en büyük Budist anıt kompleksi.',
    country: 'Endonezya',
    lat: -7.6079,
    lng: 110.2038,
    heading: 90,
    pitch: 5,
    difficulty: 'Orta',
    category: 'Endonezya'
  },
  {
    id: 'id-uluwatu',
    name: 'Uluwatu Tapınağı, Bali',
    description: 'Hint okyanusunun bembeyaz köpüklü dalgalarına bakan okyanus kıyısındaki dik falez tapınağı.',
    country: 'Endonezya',
    lat: -8.8291,
    lng: 115.0849,
    heading: 260,
    pitch: -5,
    difficulty: 'Zor',
    category: 'Endonezya'
  },
  {
    id: 'id-jakarta-monas',
    name: 'Ulusal Anıt (Monas), Cakarta',
    description: 'Endonezya bağımsızlığını simgeleyen zirvesi altın alev şeklinde anıt ve geniş meydan.',
    country: 'Endonezya',
    lat: -6.1754,
    lng: 106.8272,
    heading: 350,
    pitch: 5,
    difficulty: 'Orta',
    category: 'Endonezya'
  },
  {
    id: 'id-prambanan',
    name: 'Prambanan Tapınakları, Yogyakarta',
    description: 'Sivri kuleli muazzam Hindu tanrılarına adanmış taş tapınaklar bahçesi.',
    country: 'Endonezya',
    lat: -7.7520,
    lng: 110.4914,
    heading: 130,
    pitch: 4,
    difficulty: 'Zor',
    category: 'Endonezya'
  },

  // 16. NETHERLANDS (Hollanda)
  {
    id: 'nl-amsterdam-canal',
    name: 'Amsterdam Merkez Kanalları (Jordaan)',
    description: 'Kanal kenarlarına kilitli bisikletleri, dar ve eğik Flemenk tuğla binaları olan Amsterdam caddesi.',
    country: 'Hollanda',
    lat: 52.3721,
    lng: 4.8824,
    heading: 220,
    pitch: 0,
    difficulty: 'Kolay',
    category: 'Hollanda'
  },
  {
    id: 'nl-kinderdijk',
    name: 'Kinderdijk Yel Değirmenleri',
    description: 'Kanal boyunca sıralanmış, UNESCO koruması altındaki 18. yüzyıldan kalma devasa polder yel değirmenleri.',
    country: 'Hollanda',
    lat: 51.8887,
    lng: 4.6311,
    heading: 15,
    pitch: 2,
    difficulty: 'Orta',
    category: 'Hollanda'
  },
  {
    id: 'nl-rijksmuseum',
    name: 'Rijksmuseum Meydanı',
    description: 'Arka planda Gotik ve Rönesans esintili muazzam devlet müzesi kapısı ve yeşil büyük çim park alanı.',
    country: 'Hollanda',
    lat: 52.3592,
    lng: 4.8852,
    heading: 10,
    pitch: 5,
    difficulty: 'Kolay',
    category: 'Hollanda'
  },
  {
    id: 'nl-rotterdam',
    name: 'Erasmus Köprüsü, Rotterdam',
    description: 'Tek pilonlu, asimetrik beyaz gövdesiyle okyanus gemilerine yol açan asma "Kuğu" köprüsü.',
    country: 'Hollanda',
    lat: 51.9090,
    lng: 4.4878,
    heading: 120,
    pitch: 5,
    difficulty: 'Orta',
    category: 'Hollanda'
  },
  {
    id: 'nl-dam-square',
    name: 'Dam Meydanı, Amsterdam',
    description: 'Amsterdam\'ın tam kalbinde yer alan, arka planda görkemli Kraliyet Sarayı ve Yeni Kilise (Nieuwe Kerk) binalarının yükseldiği tarihi meydan.',
    country: 'Hollanda',
    lat: 52.3731,
    lng: 4.8926,
    heading: 270,
    pitch: 3,
    difficulty: 'Kolay',
    category: 'Hollanda'
  },
  {
    id: 'nl-cube-houses',
    name: 'Kübik Evler (Kubuswoningen), Rotterdam',
    description: 'Mimar Piet Blom tarafından tasarlanan, 45 derece eğik kollar üzerine oturtulmuş ikonik parlak sarı kübik evler caddesi.',
    country: 'Hollanda',
    lat: 51.9204,
    lng: 4.4900,
    heading: 45,
    pitch: 15,
    difficulty: 'Orta',
    category: 'Hollanda'
  },
  {
    id: 'nl-keukenhof',
    name: 'Keukenhof Bahçeleri Çevresi, Lisse',
    description: 'Milyonlarca rengarenk lale, sümbül ve nergisin açtığı, Hollanda\'nın ünlü Keukenhof lale bahçelerinin park yolu girişi.',
    country: 'Hollanda',
    lat: 52.2713,
    lng: 4.5463,
    heading: 180,
    pitch: 0,
    difficulty: 'Orta',
    category: 'Hollanda'
  },
  {
    id: 'nl-utrecht-dom',
    name: 'Dom Kulesi ve Eski Kanal, Utrecht',
    description: 'Overslag kanallarının, cafe teraslarının ve Hollanda\'nın en yüksek kilise kulesi olan Dom Tower\'ın birleştiği asil sokak.',
    country: 'Hollanda',
    lat: 52.0906,
    lng: 5.1213,
    heading: 190,
    pitch: 12,
    difficulty: 'Zor',
    category: 'Hollanda'
  },

  // 17. INDIA (Hindistan)
  {
    id: 'in-taj-front',
    name: 'Tac Mahal Havuz Yolu, Agra',
    description: 'Beyaz mermer türbe kubbesinin su bahçesine yansıdığı, Hindistan\'ın en ünlü aşk anıtı içi.',
    country: 'Hindistan',
    lat: 27.1751,
    lng: 78.0421,
    heading: 175,
    pitch: 8,
    difficulty: 'Kolay',
    category: 'Hindistan'
  },
  {
    id: 'in-hawa-mahal',
    name: 'Hawa Mahal (Rüzgarlı Saray), Jaipur',
    description: 'Kırmızı ve pembe kum taşından, 953 adet minik pencereli petek şeklinde tasarlanmış şahane saray.',
    country: 'Hindistan',
    lat: 26.9239,
    lng: 75.8267,
    heading: 270,
    pitch: 15,
    difficulty: 'Orta',
    category: 'Hindistan'
  },
  {
    id: 'in-humayun',
    name: 'Humayun Türbesi, Yeni Delhi',
    description: 'Babür imparatorluğundan kalma, Tac Mahal mimarisine ilham vermiş kırmızı tuğla dev yapı.',
    country: 'Hindistan',
    lat: 28.5933,
    lng: 77.2507,
    heading: 30,
    pitch: 5,
    difficulty: 'Orta',
    category: 'Hindistan'
  },
  {
    id: 'in-gateway-mumbai',
    name: 'Gateway of India, Mumbai',
    description: 'Umman denizine bakan, İngiliz kralının ziyareti şerefine inşa edilmiş dev bazalt zafer takı.',
    country: 'Hindistan',
    lat: 18.9220,
    lng: 72.8347,
    heading: 80,
    pitch: 4,
    difficulty: 'Kolay',
    category: 'Hindistan'
  },

  // 18. SWEDEN (İsveç)
  {
    id: 'se-gamla-stan',
    name: 'Gamla Stan (Eski Şehir), Stockholm',
    description: '17. yüzyıldan kalma daracık taş sokakları, sarı ve turuncu renkli dik çatılı kuzey binaları.',
    country: 'İsveç',
    lat: 59.3251,
    lng: 18.0708,
    heading: 140,
    pitch: 0,
    difficulty: 'Orta',
    category: 'İsveç'
  },
  {
    id: 'se-royal-palace',
    name: 'Stockholm Kraliyet Sarayı Meydanı',
    description: 'Geniş açık gri taş binalı saray avlusu ve İsveç asker nöbetçi kabinleri.',
    country: 'İsveç',
    lat: 59.3268,
    lng: 18.0717,
    heading: 320,
    pitch: 5,
    difficulty: 'Orta',
    category: 'İsveç'
  },
  {
    id: 'se-turning-torso',
    name: 'Turning Torso Kulesi, Malmö',
    description: 'Mimar Santiago Calatrava tarafından yapılan, 90 derece bükülen fütüristik kıvrımlı rezidans kulesi.',
    country: 'İsveç',
    lat: 55.6131,
    lng: 12.9765,
    heading: 140,
    pitch: 25,
    difficulty: 'Zor',
    category: 'İsveç'
  },
  {
    id: 'se-visby-wall',
    name: 'Visby Orta Çağ Surları, Gotland',
    description: 'Baltık Denizi kıyısındaki gül bahçeleri ve en iyi korunmuş İskandinav kalesi taş surları.',
    country: 'İsveç',
    lat: 57.6418,
    lng: 18.2932,
    heading: 30,
    pitch: 2,
    difficulty: 'Zor',
    category: 'İsveç'
  },
  {
    id: 'se-vasa-museum',
    name: 'Vasa Müzesi Önü, Stockholm',
    description: 'Dünyanın en iyi korunmuş 17. yüzyıl gemisinin sergilendiği, Djurgården adasındaki tuğla yapılı ünlü müze parkı yolu.',
    country: 'İsveç',
    lat: 59.3280,
    lng: 18.0914,
    heading: 260,
    pitch: 1,
    difficulty: 'Kolay',
    category: 'İsveç'
  },
  {
    id: 'se-goteborg',
    name: 'Götaplatsen Meydanı, Göteborg',
    description: 'Poseidon Çeşmesi, ünlü göteborg konser salonu ve sanatsal kuzey yapılarının bulunduğu geniş taş meydan.',
    country: 'İsveç',
    lat: 57.6969,
    lng: 11.9792,
    heading: 330,
    pitch: 4,
    difficulty: 'Orta',
    category: 'İsveç'
  },
  {
    id: 'se-uppsala-cathedral',
    name: 'Uppsala Katedrali Parkı',
    description: 'Fransa gotik tarzında inşa edilmiş kırmızı tuğla kuleli devasa katedral bahçesi ve Uppsala nehir köprüsü yan sokakları.',
    country: 'İsveç',
    lat: 59.8581,
    lng: 17.6335,
    heading: 180,
    pitch: 5,
    difficulty: 'Zor',
    category: 'İsveç'
  },
  {
    id: 'se-icehotel',
    name: 'Kutupsal Buz Oteli (Icehotel), Jukkasjärvi',
    description: 'Kuzey kutup dairesinde, karlarla kaplı nehir kıyısı ve her kış yeniden tamamen buzdan inşa edilen otel kompleksi dışı.',
    country: 'İsveç',
    lat: 67.8504,
    lng: 20.5936,
    heading: 200,
    pitch: -2,
    difficulty: 'Zor',
    category: 'İsveç'
  },

  // 19. SWITZERLAND (İsviçre)
  {
    id: 'ch-chapel-bridge',
    name: 'Chapel Köprüsü (Kapellbrücke), Luzern',
    description: 'Reuss Nehri üzerinde yer alan, içi üçgen tarihi tablolarla süslü saksı çiçekli ahşap kapalı köprü.',
    country: 'İsviçre',
    lat: 47.0516,
    lng: 8.3072,
    heading: 330,
    pitch: 3,
    difficulty: 'Kolay',
    category: 'İsviçre'
  },
  {
    id: 'ch-lauterbrunnen',
    name: 'Lauterbrunnen Şelaleli Vadi',
    description: 'Büyüleyici dik kayalıklardan dökülen dev şelale ve yeşil çimenli geleneksel İsviçre dağ evleri.',
    country: 'İsviçre',
    lat: 46.5935,
    lng: 7.9077,
    heading: 190,
    pitch: 10,
    difficulty: 'Orta',
    category: 'İsviçre'
  },
  {
    id: 'ch-zermatt',
    name: 'Matterhorn Manzaralı Zermatt',
    description: 'Arka planda Toblerone çikolatasına şekil veren piramidal kar kaplı efsane Matterhorn dağı.',
    country: 'İsviçre',
    lat: 46.0207,
    lng: 7.7491,
    heading: 230,
    pitch: 12,
    difficulty: 'Zor',
    category: 'İsviçre'
  },
  {
    id: 'ch-geneva',
    name: 'Jet d\'Eau Çeşmesi (Cenevre Gölü)',
    description: 'Gölden okyanus havasına doğru 140 metre fışkıran basınçlı dev su jeti ve Cenevre limanı.',
    country: 'İsviçre',
    lat: 46.2074,
    lng: 6.1559,
    heading: 45,
    pitch: 8,
    difficulty: 'Orta',
    category: 'İsviçre'
  },

  // 20. NORWAY (Norveç)
  {
    id: 'no-lofoten',
    name: 'Reine Balıkçı Kasabası, Lofoten',
    description: 'Kutup dairesi içerisinde, fiyort suları kenarında yükselen dik karlı kayalar ve kırmızı ahşap balıkçı kulübeleri (Rorbuer).',
    country: 'Norveç',
    lat: 67.9304,
    lng: 13.0886,
    heading: 45,
    pitch: 5,
    difficulty: 'Zor',
    category: 'Norveç'
  },
  {
    id: 'no-bryggen',
    name: 'Bryggen Tarihi Hanseatic Rıhtımı, Bergen',
    description: 'Fiyort kenarındaki eğri sıralanmış, yanmış ve restore edilmiş ikonik sarı ve kızıl üçgen ahşap depolar.',
    country: 'Norveç',
    lat: 60.3975,
    lng: 5.3246,
    heading: 45,
    pitch: 1,
    difficulty: 'Kolay',
    category: 'Norveç'
  },
  {
    id: 'no-oslo-opera',
    name: 'Oslo Opera Binası Terası',
    description: 'Sudan yükselen beyaz mermer ve cam eğimli fütüristik çatısı üzerinde yayaların gezindiği fiyort kıyısı.',
    country: 'Norveç',
    lat: 59.9075,
    lng: 10.7531,
    heading: 120,
    pitch: 5,
    difficulty: 'Orta',
    category: 'Norveç'
  },
  {
    id: 'no-geiranger',
    name: 'Geirangerfjord Seyir Noktası',
    description: 'Dik yemyeşil kayalar arasındaki şelaleli okyanus suyu fiyorduna giren kruvaziyer gemileri.',
    country: 'Norveç',
    lat: 62.1015,
    lng: 7.2056,
    heading: 260,
    pitch: -5,
    difficulty: 'Zor',
    category: 'Norveç'
  },

  // 21. UKRAINE (Ukrayna)
  {
    id: 'ua-kyiv-maidan',
    name: 'Bağımsızlık Meydanı (Maidan), Kyiv',
    description: 'Kyiv şehir merkezinde yer alan bağımsızlık sütunu ve fıskiyeli geniş Sovyetik anıtsal meydan.',
    country: 'Ukrayna',
    lat: 50.4507,
    lng: 30.5230,
    heading: 180,
    pitch: 4,
    difficulty: 'Zor',
    category: 'Ukrayna'
  },
  {
    id: 'ua-lviv-square',
    name: 'Konyusheny Caddesi / Rynok Meydanı, Lviv',
    description: 'Üzerinden tramvay hatlarının geçtiği, Latin ve Ukrayna barok binalı Arnavut kaldırımlı meydan.',
    country: 'Ukrayna',
    lat: 49.8417,
    lng: 24.0315,
    heading: 260,
    pitch: 2,
    difficulty: 'Zor',
    category: 'Ukrayna'
  },
  {
    id: 'ua-odessa-opera',
    name: 'Odessa Ulusal Opera ve Bale Tiyatrosu',
    description: 'Barok Fransız rokokosu tarzında inşa edilmiş büyüleyici tiyatro binası cephesi.',
    country: 'Ukrayna',
    lat: 46.4855,
    lng: 30.7412,
    heading: 320,
    pitch: 5,
    difficulty: 'Zor',
    category: 'Ukrayna'
  },
  {
    id: 'ua-kamianets',
    name: 'Kamianets-Podilskyi Kalesi',
    description: 'Kanyon yarığı üzerine kurulmuş çok kuleli masalsı orta çağ taş kalesi.',
    country: 'Ukrayna',
    lat: 48.6734,
    lng: 26.5630,
    heading: 45,
    pitch: 8,
    difficulty: 'Zor',
    category: 'Ukrayna'
  },

  // 22. ARGENTINA (Arjantin)
  {
    id: 'ar-buenos-aires',
    name: 'Obelisco (Dikili Taş) Meydanı, Buenos Aires',
    description: 'Dünyanın en geniş caddesi olan Avenida 9 de Julio üzerinde yükselen dev beyaz dikilitaş.',
    country: 'Arjantin',
    lat: -34.6037,
    lng: -58.3816,
    heading: 220,
    pitch: 10,
    difficulty: 'Kolay',
    category: 'Arjantin'
  },
  {
    id: 'ar-caminito',
    name: 'Caminito Sokağı (La Boca), Buenos Aires',
    description: 'Liman işçilerinin boyadığı sac levhalardan rengarenk derme tüy binaları, tango dansçıları.',
    country: 'Arjantin',
    lat: -34.6393,
    lng: -58.3628,
    heading: 100,
    pitch: 3,
    difficulty: 'Kolay',
    category: 'Arjantin'
  },
  {
    id: 'ar-glacier',
    name: 'Perito Moreno Buzulu, Patagonia',
    description: 'Uçsuz bucaksız parlayan turkuaz okyanus buzul duvarı ve karlı göl kıyısı yolu.',
    country: 'Arjantin',
    lat: -50.4938,
    lng: -73.0481,
    heading: 270,
    pitch: -2,
    difficulty: 'Zor',
    category: 'Arjantin'
  },
  {
    id: 'ar-mendoza',
    name: 'Mendoza Üzüm Bağları',
    description: 'Arka planda And Dağları sıradağları yükselen, mükemmel düz asma ağacı bağları.',
    country: 'Arjantin',
    lat: -33.0081,
    lng: -68.8682,
    heading: 250,
    pitch: 1,
    difficulty: 'Zor',
    category: 'Arjantin'
  },

  // 23. ASIA REGION (Asya Bölgesi)
  {
    id: 'asia-tokyo-skytree',
    name: 'Tokyo Skytree, Japonya',
    description: 'Dünyanın en yüksek kulesi olan ve Tokyo ovasını 360 derece izleyen fütüristik yapıt dibi.',
    country: 'Japonya',
    lat: 35.7100,
    lng: 139.8107,
    heading: 210,
    pitch: 35,
    difficulty: 'Kolay',
    category: 'Asya'
  },
  {
    id: 'asia-angkor-wat',
    name: 'Angkor Wat Tapınağı, Kamboçya',
    description: 'Kum taşından örülmüş görkemli nilüfer çiçeği kuleleri olan antik Kmer tapınak şehri.',
    country: 'Kamboçya',
    lat: 13.4125,
    lng: 103.8670,
    heading: 260,
    pitch: 5,
    difficulty: 'Zor',
    category: 'Asya'
  },
  {
    id: 'asia-petronas',
    name: 'Petronas İkiz Kuleleri, Malezya',
    description: 'Kuala Lumpur başkentinde göğe uzanan çelik yapılı, ortasında bağlantı köprüsü olan dev ikiz gökdelen kuleler.',
    country: 'Malezya',
    lat: 3.1578,
    lng: 101.7119,
    heading: 10,
    pitch: 35,
    difficulty: 'Kolay',
    category: 'Asya'
  },
  {
    id: 'asia-great-wall',
    name: 'Çin Seddi (Mutianyu Bölümü)',
    description: 'Yemyeşil dik dağ zirveleri boyunca ejderha gibi kıvrılarak uzanan taş gözetleme kuleli efsanevi Çin suru.',
    country: 'Çin',
    lat: 40.4319,
    lng: 116.5704,
    heading: 120,
    pitch: 5,
    difficulty: 'Zor',
    category: 'Asya'
  },

  // 24. EUROPE REGION (Avrupa Bölgesi)
  {
    id: 'eur-neuschwan',
    name: 'Neuschwanstein Şatosu Görünümü',
    description: 'Almanya Bavyera dağlarında yükselen masalsı kuleli Orta Çağ esintili ünlü şato.',
    country: 'Almanya',
    lat: 47.5576,
    lng: 10.7498,
    heading: 100,
    pitch: 10,
    difficulty: 'Kolay',
    category: 'Avrupa'
  },
  {
    id: 'eur-acropolis',
    name: 'Akropolis Parthenon Tapınağı, Atina',
    description: 'Yüksek tepe üzerinde yükselen, antik Yunan klasik mimarisinin simgesi olan mermer sütunlu mabet.',
    country: 'Yunanistan',
    lat: 37.9715,
    lng: 23.7266,
    heading: 200,
    pitch: 8,
    difficulty: 'Orta',
    category: 'Avrupa'
  },
  {
    id: 'eur-charles-bridge',
    name: 'Charles Köprüsü, Prag',
    description: 'Vltava nehri üzerinde, iki yanında Gotik heykeller yükselen tarihi ve muhteşem taş kemer köprü.',
    country: 'Çekya',
    lat: 50.0865,
    lng: 14.4114,
    heading: 80,
    pitch: 3,
    difficulty: 'Kolay',
    category: 'Avrupa'
  },
  {
    id: 'eur-hallstatt',
    name: 'Hallstatt Göl Kenarı, Avusturya',
    description: 'Karlı Alpler önündeki sakin ayna gibi göl kıyısında yükselen dik üçgen çatılı evler kilisesi.',
    country: 'Avusturya',
    lat: 47.5622,
    lng: 13.6493,
    heading: 340,
    pitch: 5,
    difficulty: 'Orta',
    category: 'Avrupa'
  },
  {
    id: 'eur-san-marco',
    name: 'San Marco Meydanı Campanile, Venedik',
    description: 'Venedik dükler sarayı önündeki, güvercinleri ve devasa tuğla kırmızı çan kulesiyle ünlü büyük sahil meydanı.',
    country: 'İtalya',
    lat: 45.4342,
    lng: 12.3385,
    heading: 300,
    pitch: 10,
    difficulty: 'Kolay',
    category: 'Avrupa'
  },

  // DECORATIVE Fallbacks or Extra diversity for streets
  {
    id: 'st-barcelona-gracia',
    name: 'İspanya, Barselona (Gracia Caddeleri)',
    description: 'Arnavut kaldırımlı dar fenerli sokaklar ve İspanyolca dükkan afişleri.',
    country: 'İspanya',
    lat: 41.4029,
    lng: 2.1568,
    heading: 90,
    pitch: 0,
    difficulty: 'Orta',
    category: 'Sokaklar'
  },
  {
    id: 'st-paris-marais',
    name: 'Fransa, Paris (Le Marais)',
    description: 'Tarihi Fransız kapıları, dar kaldırım kenarları ve Fransızca bistro tabelaları.',
    country: 'Fransa',
    lat: 48.8580,
    lng: 2.3621,
    heading: 10,
    pitch: 0,
    difficulty: 'Orta',
    category: 'Sokaklar'
  }
];
